name: Periodic healthcheck

on:
  schedule:
    - cron:  '0 0-23 * * *'

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://cryptic-woodland-92575.herokuapp.com