name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cryptic-woodland-92575"
          heroku_email: "jasse.nousiainen@gmail.com"
          healthcheck: "https://cryptic-woodland-92575.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true